export const data = [
  {
    id: 1,
    name: "Nexia 3 eshik",
    price: "$110",
    number: 10,
    location: "Toshkent",
    category: "Nexia",
    image: "",
  },
  {
    id: 2,
    name: "Cobalt krilo",
    price: "$60",
    number: 20,
    location: "Namangan",
    category: "Cobalt",
    image: "",
  },
  {
    id: 3,
    name: "Spark rul",
    price: "$45",
    number: 15,
    location: "Namangan",
    category: "Spark",
    image: "",
  },
  {
    id: 4,
    name: "Malibu oynasi",
    price: "$120",
    number: 8,
    location: "Toshkent",
    category: "Malibu",
    image: "",
  },
  {
    id: 5,
    name: "Gentra bamperi",
    price: "$200",
    number: 12,
    location: "Namangan",
    category: "Gentra",
    image: "",
  },
  {
    id: 6,
    name: "Lacetti farasi",
    price: "$85",
    number: 14,
    location: "Toshkent",
    category: "Lacetti",
    image: "",
  },
  {
    id: 7,
    name: "Nexia 2 kapoti",
    price: "$110",
    number: 9,
    location: "Namangan",
    category: "Nexia",
    image: "",
  },
  {
    id: 8,
    name: "Cobalt eshigi",
    price: "$130",
    number: 7,
    location: "Toshkent",
    category: "Cobalt",
    image: "",
  },
  {
    id: 9,
    name: "Spark bamperi",
    price: "$75",
    number: 11,
    location: "Namangan",
    category: "Spark",
    image: "",
  },
  {
    id: 10,
    name: "Malibu rul",
    price: "$95",
    number: 6,
    location: "Toshkent",
    category: "Malibu",
    image: "",
  },
  {
    id: 11,
    name: "Gentra oynasi",
    price: "$70",
    number: 10,
    location: "Namangan",
    category: "Gentra",
    image: "",
  },
  {
    id: 12,
    name: "Lacetti orqa farasi",
    price: "$65",
    number: 16,
    location: "Toshkent",
    category: "Lacetti",
    image: "",
  },
  {
    id: 13,
    name: "Nexia 3 bamperi",
    price: "$150",
    number: 13,
    location: "Namangan",
    category: "Nexia",
    image: "",
  },
  {
    id: 14,
    name: "Cobalt kapoti",
    price: "$115",
    number: 9,
    location: "Toshkent",
    category: "Cobalt",
    image: "",
  },
  {
    id: 15,
    name: "Spark radiator",
    price: "$90",
    number: 5,
    location: "Namangan",
    category: "Spark",
    image: "",
  },
  {
    id: 16,
    name: "Malibu orqa bamper",
    price: "$210",
    number: 7,
    location: "Toshkent",
    category: "Malibu",
    image: "",
  },
  {
    id: 17,
    name: "Gentra kapoti",
    price: "$135",
    number: 8,
    location: "Namangan",
    category: "Gentra",
    image: "",
  },
  {
    id: 18,
    name: "Lacetti eshigi",
    price: "$140",
    number: 10,
    location: "Toshkent",
    category: "Lacetti",
    image: "",
  },
  {
    id: 19,
    name: "Nexia 2 oynasi",
    price: "$55",
    number: 12,
    location: "Namangan",
    category: "Nexia",
    image: "",
  },
  {
    id: 20,
    name: "Cobalt orqa bamper",
    price: "$160",
    number: 9,
    location: "Toshkent",
    category: "Cobalt",
    image: "",
  },
  {
    id: 21,
    name: "Spark kapoti",
    price: "$100",
    number: 10,
    location: "Namangan",
    category: "Spark",
    image: "",
  },
  {
    id: 22,
    name: "Malibu radiator",
    price: "$125",
    number: 11,
    location: "Toshkent",
    category: "Malibu",
    image: "",
  },
  {
    id: 23,
    name: "Gentra bamperi",
    price: "$180",
    number: 15,
    location: "Namangan",
    category: "Gentra",
    image: "",
  },
  {
    id: 24,
    name: "Lacetti rul",
    price: "$60",
    number: 14,
    location: "Toshkent",
    category: "Lacetti",
    image: "",
  },
  {
    id: 25,
    name: "Nexia 3 radiator",
    price: "$95",
    number: 9,
    location: "Namangan",
    category: "Nexia",
    image: "",
  },
  {
    id: 26,
    name: "Cobalt rul",
    price: "$75",
    number: 8,
    location: "Toshkent",
    category: "Cobalt",
    image: "",
  },
  {
    id: 27,
    name: "Spark orqa farasi",
    price: "$55",
    number: 10,
    location: "Namangan",
    category: "Spark",
    image: "",
  },
  {
    id: 28,
    name: "Malibu eshigi",
    price: "$150",
    number: 6,
    location: "Toshkent",
    category: "Malibu",
    image: "",
  },
  {
    id: 29,
    name: "Gentra oynasi",
    price: "$70",
    number: 12,
    location: "Namangan",
    category: "Gentra",
    image: "",
  },
  {
    id: 30,
    name: "Lacetti bamperi",
    price: "$100",
    number: 13,
    location: "Toshkent",
    category: "Lacetti",
    image: "",
  },
  {
    id: 31,
    name: "Nexia 2 rul",
    price: "$65",
    number: 8,
    location: "Namangan",
    category: "Nexia",
    image: "",
  },
  {
    id: 32,
    name: "Cobalt radiator",
    price: "$115",
    number: 9,
    location: "Toshkent",
    category: "Cobalt",
    image: "",
  },
  {
    id: 33,
    name: "Spark bamperi",
    price: "$85",
    number: 11,
    location: "Namangan",
    category: "Spark",
    image: "",
  },
];

export const carModels = ["Nexia", "Cobalt", "Spark", "Malibu", "Gentra", "Lacetti"];
export const carLocations = ["Toshkent", "Namangan"];
export const adminCode = "1272";
